In [1]:
pip install mysql-connector-python

  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/a7/84/b63f11124f808b6f1e3389072bc36cc907929d7574e85f94bf8f18117fe4/mysql_connector_python-8.2.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
     ----- --------------------------------- 71.7/527.0 kB 2.0 MB/s eta 0:00:01
     ---------- --------------------------- 143.4/527.0 kB 2.1 MB/s eta 0:00:01
     ------------ ------------------------- 174.1/527.0 kB 1.7 MB/s eta 0:00:01
     -------------------- ----------------- 286.7/527.0 kB 2.0 MB/s eta 0:00:01
     ------------------------- ------------ 358.4/527.0 kB 1.6 MB/s eta 0:00:01
     -------------------------------- ----- 450.6/527.0 kB 1.8 MB/s eta 0:00:01
     -------------------------------- ----- 450.6/527.0 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 527.0/527.0 kB 1.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1

In [12]:
import numpy as np

In [2]:
import mysql.connector

In [19]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root",
  database="bhumi"
)


mycursor = mydb.cursor()

mycursor.execute("select * from orders")

result = mycursor.fetchall()
 
print(result)


[(1, 1, 1, 2, datetime.datetime(2022, 3, 8, 14, 25)), (2, 2, 1, 1, datetime.datetime(2022, 3, 7, 9, 32)), (3, 3, 3, 4, datetime.datetime(2022, 3, 6, 18, 5)), (4, 4, 5, 3, datetime.datetime(2022, 3, 5, 10, 12)), (5, 5, 2, 2, datetime.datetime(2022, 3, 4, 15, 22)), (6, 1, 3, 1, datetime.datetime(2022, 3, 3, 12, 48)), (7, 2, 4, 2, datetime.datetime(2022, 3, 2, 17, 9)), (8, 3, 1, 3, datetime.datetime(2022, 3, 1, 11, 35)), (9, 4, 2, 1, datetime.datetime(2022, 2, 28, 16, 2)), (10, 5, 5, 2, datetime.datetime(2022, 2, 27, 13, 24)), (11, 1, 2, 3, datetime.datetime(2022, 2, 26, 10, 49)), (12, 2, 3, 2, datetime.datetime(2022, 2, 25, 14, 56)), (13, 3, 4, 1, datetime.datetime(2022, 2, 24, 9, 17)), (14, 4, 1, 2, datetime.datetime(2022, 2, 23, 12, 40)), (15, 5, 3, 3, datetime.datetime(2022, 2, 22, 16, 58))]


In [23]:
for x in result:
  print(x)

(1, 1, 1, 2, datetime.datetime(2022, 3, 8, 14, 25))
(2, 2, 1, 1, datetime.datetime(2022, 3, 7, 9, 32))
(3, 3, 3, 4, datetime.datetime(2022, 3, 6, 18, 5))
(4, 4, 5, 3, datetime.datetime(2022, 3, 5, 10, 12))
(5, 5, 2, 2, datetime.datetime(2022, 3, 4, 15, 22))
(6, 1, 3, 1, datetime.datetime(2022, 3, 3, 12, 48))
(7, 2, 4, 2, datetime.datetime(2022, 3, 2, 17, 9))
(8, 3, 1, 3, datetime.datetime(2022, 3, 1, 11, 35))
(9, 4, 2, 1, datetime.datetime(2022, 2, 28, 16, 2))
(10, 5, 5, 2, datetime.datetime(2022, 2, 27, 13, 24))
(11, 1, 2, 3, datetime.datetime(2022, 2, 26, 10, 49))
(12, 2, 3, 2, datetime.datetime(2022, 2, 25, 14, 56))
(13, 3, 4, 1, datetime.datetime(2022, 2, 24, 9, 17))
(14, 4, 1, 2, datetime.datetime(2022, 2, 23, 12, 40))
(15, 5, 3, 3, datetime.datetime(2022, 2, 22, 16, 58))


In [24]:
import pandas as pd

In [25]:
from datetime import datetime


In [30]:
Data = [
    (1, 1, 1, 2, datetime(2022, 3, 8, 14, 25)),
    (2, 2, 1, 1, datetime(2022, 3, 7, 9, 32)),
    (3, 3, 3, 4, datetime(2022, 3, 6, 18, 5)),
    (4, 4, 5, 3, datetime(2022, 3, 5, 10, 12)),
    (5, 5, 2, 2, datetime(2022, 3, 4, 15, 22)),
    (6, 1, 3, 1, datetime(2022, 3, 3, 12, 48)),
    (7, 2, 4, 2, datetime(2022, 3, 2, 17, 9)),
    (8, 3, 1, 3, datetime(2022, 3, 1, 11, 35)),
    (9, 4, 2, 1, datetime(2022, 2, 28, 16, 2)),
    (10, 5, 5, 2, datetime(2022, 2, 27, 13, 24)),
    (11, 1, 2, 3, datetime(2022, 2, 26, 10, 49)),
    (12, 2, 3, 2, datetime(2022, 2, 25, 14, 56)),
    (13, 3, 4, 1, datetime(2022, 2, 24, 9, 17)),
    (14, 4, 1, 2, datetime(2022, 2, 23, 12, 40)),
    (15, 5, 3, 3, datetime(2022, 2, 22, 16, 58))
    
]
columns = ["id","cutomer_id","pruduct_id","quanity","order_date"]

df = pd.DataFrame(Data,columns=columns)

print(df)

    id  cutomer_id  pruduct_id  quanity          order_date
0    1           1           1        2 2022-03-08 14:25:00
1    2           2           1        1 2022-03-07 09:32:00
2    3           3           3        4 2022-03-06 18:05:00
3    4           4           5        3 2022-03-05 10:12:00
4    5           5           2        2 2022-03-04 15:22:00
5    6           1           3        1 2022-03-03 12:48:00
6    7           2           4        2 2022-03-02 17:09:00
7    8           3           1        3 2022-03-01 11:35:00
8    9           4           2        1 2022-02-28 16:02:00
9   10           5           5        2 2022-02-27 13:24:00
10  11           1           2        3 2022-02-26 10:49:00
11  12           2           3        2 2022-02-25 14:56:00
12  13           3           4        1 2022-02-24 09:17:00
13  14           4           1        2 2022-02-23 12:40:00
14  15           5           3        3 2022-02-22 16:58:00


In [34]:
arr=np.array(Data)

In [35]:
arr[:5,4:]

array([[datetime.datetime(2022, 3, 8, 14, 25)],
       [datetime.datetime(2022, 3, 7, 9, 32)],
       [datetime.datetime(2022, 3, 6, 18, 5)],
       [datetime.datetime(2022, 3, 5, 10, 12)],
       [datetime.datetime(2022, 3, 4, 15, 22)]], dtype=object)

In [37]:
arr[::2]

array([[1, 1, 1, 2, datetime.datetime(2022, 3, 8, 14, 25)],
       [3, 3, 3, 4, datetime.datetime(2022, 3, 6, 18, 5)],
       [5, 5, 2, 2, datetime.datetime(2022, 3, 4, 15, 22)],
       [7, 2, 4, 2, datetime.datetime(2022, 3, 2, 17, 9)],
       [9, 4, 2, 1, datetime.datetime(2022, 2, 28, 16, 2)],
       [11, 1, 2, 3, datetime.datetime(2022, 2, 26, 10, 49)],
       [13, 3, 4, 1, datetime.datetime(2022, 2, 24, 9, 17)],
       [15, 5, 3, 3, datetime.datetime(2022, 2, 22, 16, 58)]],
      dtype=object)

In [38]:
arr[::-1]

array([[15, 5, 3, 3, datetime.datetime(2022, 2, 22, 16, 58)],
       [14, 4, 1, 2, datetime.datetime(2022, 2, 23, 12, 40)],
       [13, 3, 4, 1, datetime.datetime(2022, 2, 24, 9, 17)],
       [12, 2, 3, 2, datetime.datetime(2022, 2, 25, 14, 56)],
       [11, 1, 2, 3, datetime.datetime(2022, 2, 26, 10, 49)],
       [10, 5, 5, 2, datetime.datetime(2022, 2, 27, 13, 24)],
       [9, 4, 2, 1, datetime.datetime(2022, 2, 28, 16, 2)],
       [8, 3, 1, 3, datetime.datetime(2022, 3, 1, 11, 35)],
       [7, 2, 4, 2, datetime.datetime(2022, 3, 2, 17, 9)],
       [6, 1, 3, 1, datetime.datetime(2022, 3, 3, 12, 48)],
       [5, 5, 2, 2, datetime.datetime(2022, 3, 4, 15, 22)],
       [4, 4, 5, 3, datetime.datetime(2022, 3, 5, 10, 12)],
       [3, 3, 3, 4, datetime.datetime(2022, 3, 6, 18, 5)],
       [2, 2, 1, 1, datetime.datetime(2022, 3, 7, 9, 32)],
       [1, 1, 1, 2, datetime.datetime(2022, 3, 8, 14, 25)]], dtype=object)

In [42]:
arr[:11,:]

array([[2, 2, 1, 1, datetime.datetime(2022, 3, 7, 9, 32)],
       [3, 3, 3, 4, datetime.datetime(2022, 3, 6, 18, 5)],
       [4, 4, 5, 3, datetime.datetime(2022, 3, 5, 10, 12)],
       [5, 5, 2, 2, datetime.datetime(2022, 3, 4, 15, 22)],
       [6, 1, 3, 1, datetime.datetime(2022, 3, 3, 12, 48)],
       [7, 2, 4, 2, datetime.datetime(2022, 3, 2, 17, 9)],
       [8, 3, 1, 3, datetime.datetime(2022, 3, 1, 11, 35)],
       [9, 4, 2, 1, datetime.datetime(2022, 2, 28, 16, 2)],
       [10, 5, 5, 2, datetime.datetime(2022, 2, 27, 13, 24)],
       [11, 1, 2, 3, datetime.datetime(2022, 2, 26, 10, 49)]],
      dtype=object)